### ISSUE TITLE
Curve Bug

### ISSUE THREAD

**Issue by JimmenyKricket2020** [curvefi/curve-contract#19]
Hello,

I'm new to the Synthetic Network and it seems that I have an issue with some crypto that I have deposited into the Curve Pool and I can't get it to come out. I see there is a notice about a recent bug, and I have tried to do the transaction through my Mintr Console but that does seem to be working or showing any results either.

I do have a screenshot to share with you down below.

John Wann
jwannjr@gmail.com

![Screenshot_2020-08-16 curve fi susd](https://user-images.githubusercontent.com/67905650/90321245-8181e800-df7a-11ea-9994-a4447f2dc781.png)

**Comment by iamdefinitelyahuman** [comment]
Closing this for now as Github issues are intended for development and bug reports.

If you still require assistance, feel free to contact us via one of the following:

* Telegram - https://t.me/curvefi
* Discord - https://discord.gg/rgrfS7W
