### ISSUE TITLE
Make get_dy and exchange have a consistent logic of computing dy in sUSD pool

### ISSUE THREAD

**Issue by manhlx3006** [curvefi/curve-contract#51]
### Overview

In sUSD pool [code](https://github.com/curvefi/curve-contract/blob/master/contracts/pools/susd/StableSwapSUSD.vy), **get_dy()** and **exchange()** have an inconsistent logic of computing **_dy** amount, thus, the returned amount in **exchange()** could be different from the returned value of **get_dy()**.

In [get_dy()](https://github.com/curvefi/curve-contract/blob/ac83e107299a22bbee5b2991ddea718b8b0249e7/contracts/pools/susd/StableSwapSUSD.vy#L381) function:
```
dy: uint256 = (xp[j] - y) * PRECISION / rates[j]
_fee: uint256 = self.fee * dy / FEE_DENOMINATOR
_dy: uint256 = dy - _fee
```

In [exchange()](https://github.com/curvefi/curve-contract/blob/ac83e107299a22bbee5b2991ddea718b8b0249e7/contracts/pools/susd/StableSwapSUSD.vy#L412) function:
```
dy: uint256 = xp[j] - y
dy_fee: uint256 = dy * self.fee / FEE_DENOMINATOR
_dy: uint256 = (dy - dy_fee) * PRECISION / rates[j]
```

### Specification
Should make the same logic of computing **_dy** value in both functions.

**Comment by michwill** [comment]
Cannot change code of already working pools. But good catch - will be fixed in new ones (I think I actually did)

**Comment by iamdefinitelyahuman** [comment]
This was addressed in a later contract and is fixed in our templates.  Thank you for mentioning tho! :pray:
