### ISSUE TITLE
get_dy_underlying does not factor in rate of underlying token

### ISSUE THREAD

**Issue by terencechow** [curvefi/curve-contract#72]
### What was wrong?

`get_dy_underlying` passes in an `x` into `get_y` that differs from the `x` that `exchange_underlying` passes. I believe this means `get_dy_underlying` will not be accurate since it doesn't factor in the rate.

Specifically in line 409 and 437 of the [curve compound pool](https://github.com/curvefi/curve-contract/blob/master/contracts/pools/compound/StableSwapCompound.vy) you can see what is passed in to each:

```
get_dy_underlying(...):
    x = xp[i] + dx * precisions[i]

...

_exchange(...)
    x = xp[i] + dx * rates[i] / PRECISION  # Note: rates[i] is defined in _current_rates as precisions[i] * cERC20().exchangeRateCurrent
...

```

I believe this means that `get_dy_underlying` does not factor in the rate of the underlying token and therefore always gives an incorrect amount of output given dx. I would have expected that line to be ` x = xp[i] + dx * rates[i] / PRECISION`, where `rates[i]` comes from `_stored_rates`. Although the `stored_rates` is not the same as 'current_rates', I suspect it should be more accurate then not multiplying any rates at all?

Am I understanding this correctly? I am attempting to estimate dy given dx as accurate as possible, so If `get_dy_underlying` would be more accurate factoring in the stored rates, I can modify the dx I pass into the `get_dy_underlying` call so that it factors in `stored_rates`. (I.e. I will call out to the cERC20 token myself and multiple that to dx and use that new dx in my `get_dy_underlying` if it is more accurate)

### How can it be fixed?

I believe the solution is to add `x = xp[i] + dx * rates[i] / PRECISION` into the `get_dy_underlying` to make it more representative of what `exchange_underlying` is doing, but I leave this up to the actual maintainers of the code to confirm this since I'm not 100% familiar with this.

Note I noticed this across all the pools that I looked at and I suspect the code was copy and pasted across each code base.

**Comment by michwill** [comment]
Actually this is no mistake.

When we work with "wrapped" assets, you need to multiply both balances and dx by rates. And rates get you to the "underlying units".

However when you work with underlying units _already_, dx doesn't need this conversion. That's why get_dy_underlying doesn't have it and get_dy does
